version: 2.1
orbs:
  codecov: codecov/codecov@3

jobs:
  build:
    docker:
      - image: wholetale/girder:latest
      - image: mongo:3.4
    environment:
      PLUGIN: synced_folders
    steps:
      - checkout
      - run:
          name: Installing Plugin Dependencies
          command: |
            rm -rf /girder/plugins/${PLUGIN}
            ln -s /root/project /girder/plugins/${PLUGIN}
            # set -o pipefail; python3 -m pip install --upgrade --force-reinstall -r requirements.txt -r requirements-dev.txt | cat
      - run:
          name: Install Test Dependencies
          environment:
            - LC_ALL: "C.UTF-8"
          command: |
            set -o pipefail; cd /girder ; python3 -m pip install -r requirements-dev.txt -e .[plugins,sftp] | cat
            set -o pipefail; cd /girder/pytest_girder ; python3 -m pip install . | cat
            cp /root/project/setup.cfg /girder/
      - run:
          name: Running Tests
          environment:
            - PYTHON_VERSION: "3.9"
            - COVERAGE_EXECUTABLE: "/girder/venv/bin/coverage"
            - FLAKE8_EXECUTABLE: "/girder/venv/bin/flake8"
            - VIRTUALENV_EXECUTABLE: "/girder/venv/bin/virtualenv"
            - PYTHON_EXECUTABLE: "/girder/venv/bin/python3"
            - TEST_GROUP: "python"
            - GIRDER_WT_EVENT_EXP_SECONDS: 60
          command: |
            mkdir /girder/build
            ctest -VV -S /girder/plugins/${PLUGIN}/cmake/circle_continuous.cmake
      - run:
          name: Collect coverage reports
          command: coverage combine /girder/build/test/coverage/python_temp/
      - codecov/upload
